function connection = so_empty_connection()
%SO_EMPTY_CONNECTION Canonical failed connection object.
connection.success = false;
connection.nForward = NaN;
connection.nBackward = NaN;
connection.totalIterations = Inf;
connection.tauResolved = Inf;
connection.control = NaN;
connection.controlledInitialState = [NaN; NaN];
connection.targetComponent = "";
connection.targetPhasePointIndex = NaN;
connection.targetChainID = "";
connection.targetBoundaryParameter = NaN;
connection.targetBoundaryPoint = [NaN; NaN];
connection.intersectionPoint = [NaN; NaN];
connection.intersectionResidual = Inf;
connection.plannedPath = [];
connection.finalState = [NaN; NaN];
connection.targetContained = false;
connection.resolvablePairMask = [];
connection.splitStatus = strings(0, 0);
connection.resolutionFailures = table();
connection.diagnostics = struct();
connection.resolvableForwardEnvelope = NaN;
connection.resolvableBackwardEnvelope = NaN;
connection.resolutionHoles = 0;
connection.timeMinimumCertified = false;
connection.selectionCertified = false;
connection.directContainment = false;
end
