function tbl = so_stage_summary_table(result)
%SO_STAGE_SUMMARY_TABLE Compact stage diagnostics.
rows = {};
for i = 1:numel(result.stagePlans)
    s = result.stagePlans(i);
    c = s.provisionalConnection;
    rows(end + 1, :) = {s.stage, string(s.targetKind), string(s.targetID), ...
        s.rotationNumber, c.success, c.nForward, c.nBackward, c.totalIterations, ...
        c.control, c.targetComponent, c.targetPhasePointIndex, ...
        c.intersectionResidual, c.targetContained, s.selectedSwitchIndex, s.skipped, ...
        c.timeMinimumCertified, c.selectionCertified, c.resolutionHoles}; %#ok<AGROW>
end
names = {'stage','targetKind','targetID','rotationNumber','connectionSuccess', ...
    'nForward','nBackward','tauResolved','controlY','targetComponent', ...
    'targetPhasePointIndex','intersectionResidual','targetContained', ...
    'selectedSwitchIndex','skipped','timeMinimumCertified','selectionCertified', ...
    'resolutionHoles'};
if isempty(rows)
    tbl = cell2table(cell(0, numel(names)), 'VariableNames', names);
else
    tbl = cell2table(rows, 'VariableNames', names);
end
end

